version: '3'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    restart: always
    environment:
      - MARIADB_ENABLE_SLOW_QUERY=1
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_USER=${DB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_INNODB_LOG_FILE_SIZE=1G
      - MARIADB_TMP_TABLE_SIZE=256M
      - MARIADB_MAX_HEAP_TABLE_SIZE=256M
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=1550
      - TZ=Asia/Bangkok
      - BITNAMI_DEBUG=true
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - './mariadb_data:/bitnami/mariadb'
volumes:
  mariadb_data:
    driver: local
